file_format: "1"
id: corne_v3
name: Corne
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - corne_v3_left
  - corne_v3_right
